/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.Turma_AlunoControl;
import modelo.Turma_Aluno;
import javax.swing.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import view.FrmAluno;
import view.FrmTurma;

/**
 *
 * @author User
 */
public class FrmTurmaAluno extends javax.swing.JFrame {

    /**
     * Creates new form FrmTurmaAluno
     */
    
    private final Turma_AlunoControl turmaAlunoControl = new Turma_AlunoControl();
    
    public FrmTurmaAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFkAluno = new javax.swing.JTextField();
        txtFkTurma = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTurmaAluno = new javax.swing.JTable();
        btnGerAluno = new javax.swing.JButton();
        btnGerTurma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gerenciamento Turma Aluno");

        jLabel2.setText("fk_aluno (id)");

        jLabel3.setText("fk_turma (id)");

        btnAdicionar.setText("Adcionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        tblTurmaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "fk_aluno", "Aluno", "fk_turma"
            }
        ));
        jScrollPane1.setViewportView(tblTurmaAluno);

        btnGerAluno.setText("Gerenciamento de Aluno");
        btnGerAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerAlunoActionPerformed(evt);
            }
        });

        btnGerTurma.setText("Gerenciamento de Turma");
        btnGerTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerTurmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFkAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFkTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGerAluno)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGerTurma))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(btnAdicionar)
                                .addGap(63, 63, 63)
                                .addComponent(btnListar)))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerAluno)
                    .addComponent(btnGerTurma))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFkAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFkTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnListar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listarTurmas();
    }//GEN-LAST:event_btnListarActionPerformed

    private void listarTurmas() {
    // Recupera a lista de Turma_Aluno
    List<Turma_Aluno> turmaAlunos = turmaAlunoControl.listar(""); // Modifique conforme necessário

    // Obtém o modelo da tabela
    DefaultTableModel model = (DefaultTableModel) tblTurmaAluno.getModel();
    model.setRowCount(0); // Limpa a tabela antes de adicionar novos dados

    // Adiciona os dados à tabela
    for (Turma_Aluno ta : turmaAlunos) {
        // Busca o nome do aluno pelo ID (fk_aluno)
        String nomeAluno = turmaAlunoControl.obterNomeAlunoPorId(ta.getFk_aluno());
        
        model.addRow(new Object[]{ta.getFk_aluno(), nomeAluno, ta.getFk_turma()});
    }
}
   
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        try {
            int fkAluno = Integer.parseInt(txtFkAluno.getText());
            int fkTurma = Integer.parseInt(txtFkTurma.getText());
            turmaAlunoControl.adicionar(fkAluno, fkTurma);
            JOptionPane.showMessageDialog(this, "Aluno adicionado à turma com sucesso!");
            txtFkAluno.setText(""); // Limpar o campo após adicionar
            txtFkTurma.setText(""); // Limpar o campo após adicionar
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira valores válidos.");
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnGerAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerAlunoActionPerformed
         
    FrmAluno frmAluno = new FrmAluno();
    
    frmAluno.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_btnGerAlunoActionPerformed

    private void btnGerTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerTurmaActionPerformed
    
    FrmTurma frmTurma = new FrmTurma();
    
    frmTurma.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_btnGerTurmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTurmaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTurmaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTurmaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTurmaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTurmaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnGerAluno;
    private javax.swing.JButton btnGerTurma;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTurmaAluno;
    private javax.swing.JTextField txtFkAluno;
    private javax.swing.JTextField txtFkTurma;
    // End of variables declaration//GEN-END:variables
}
